Add more overloads to IEventBus for optional parameters.
neoforged/Bus pull request #8
Opened 2023-08-06 15:26 UTC by ApexModder

Adds remaining overloads to match the following patterns
_`[...] - meaning optional`_
- `addListener([priority], [receiveCancelled], [eventType], consumer)`
- `addGenericListener(genericClassFilter, [priority], [receiveCancelled], [eventType], consumer)`

Updated tests to use these new overloads rather than passing in the default `priority` / `receiveCancelled` values.

2023-08-07 11:17 UTC, Technici4n commented
I want to remove generic events. But that doesn't mean this PR can't be merged - the added functions can be removed when we remove generic events.

2023-08-08 09:24 UTC, Technici4n approved these changes

2023-08-17 13:06 UTC, Matyrobbrt requested changes

2023-08-17 13:06 UTC, Matyrobbrt commented on src/main/java/net/minecraftforge/eventbus/EventBus.java
> +        checkNotGeneric(eventType);
Please remove the `checkNotGeneric` tests. `addListener(EventPriority, Class, Z, Consumer)` already checks for generic-ity.

2023-08-17 13:10 UTC, Technici4n requested changes
Two requests after all:
- Do not add the generic event overloads, they will be deprecated for removal soon.
- The method order is weird IMO; I would place each `Class`-taking method right after the corresponding non-`Class`-taking method.

2023-08-17 19:30 UTC, Technici4n approved these changes

2023-08-18 07:20 UTC, Matyrobbrt approved these changes

2023-08-18 18:34 UTC, merged